authSection/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authSection'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
]

mainSection/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'mainSection'

urlpatterns = [
    path('home/', views.home, name="home"),
    path('createshipment/', views.createshipment, name="createshipment"),
    path('home/createshipment/saveshipment/', views.saveshipment, name="saveshipment"),
    path('fillshipment/', views.fillshipment, name="fillshipment"),
    path('saveproduct/', views.saveproduct, name="saveproduct"),
    path('viewhipment/', views.viewshipment, name="viewshipment"),
    path('reviewshipment/', views.reviewShipment, name="reviewshipment"),
    path('costfactor/', views.generateCostFactor, name="costfactor"),
    path('deleteshipmentdetail/<int:pk>', views.deleteshipmentdetail, name="deleteshipmentdetail"),
    path('finalizeshipment/', views.finalizeshipment, name="finalizeshipment"),
    path('updateproduct/<int:pk>/', views.updateproduct, name="updateproduct"),
    path('applyCost/', views.applyCost, name="applyCost"),
    path('viewproduct/', views.viewproduct, name="viewproduct"),
    path('grn/', views.grnstore, name="grnstore"),
    path('grn/<int:pk>/', views.updateproductgrn, name="updateproductgrn"),
    path('closeshipment', views.closeshipment, name="closeshipment"),
    path('customers/', views.loadCustomer, name="loadCustomer"),
    path('savecustomers/', views.savecustomers, name="savecustomers"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shadesProductUploader/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('mainSection.urls')),
    path('admin/', admin.site.urls),
    path('',include('authSection.urls')),
    
] 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>eRetail | Dashboard</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'css/skins/_all-skins.min.css' %}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{% static 'css/morris.css' %}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{% static 'css/jquery-jvectormap.css' %}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{% static 'css/bootstrap3-wysihtml5.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- Styles related to Loader-->
    <style>
        #loading {
            width: 100%;
            height: 100%;
            top: 0px;
            left: 0px;
            position: fixed;
            display: block;
            z-index: 99;
            opacity: 0.7;
            background-color: #fff;
        }

        #loading-image {
            position: absolute;
            top: 40%;
            left: 45%;
            z-index: 100
        }
    </style>
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div id="loading">
    <img id="loading-image" src="{% static 'images/ajax-loader.gif' %}" alt="Loading..."/>
</div>

<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>e</b>R</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>e</b>Retail</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="btn btn-primary" data-toggle="push-menu" role="button">
                <i class="fas fa-align-left"></i>
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="col-6 text-right">
                {% if user.is_authenticated %}
                    <p class="pt-3">Logged in as <strong>{{ user.username }}</strong> | <a class="text-dark"
                                                                                           href="{% url 'authSection:logout' %}">Log
                        out</a>.</p>
                {% else %}
                    <a href="{% url 'authSection:login' %}" class="btn btn-light" role="button">Log in</a>
                {% endif %}
            </div>

        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">


            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>
                <li class="treeview">
                    <a href="#">
                        <i class="fas fa-plane-departure"></i> <span> Shipments</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'mainSection:createshipment' %}"><i class="fas fa-plus-circle"></i>
                            Create Shipment</a></li>
                        <li><a id="fillShipmentLink" href="{% url 'mainSection:fillshipment' %}"><i
                                class="fa fa-ship"></i>
                            Fill Shipment</a></li>
                        <li><a href="{% url 'mainSection:viewshipment' %}"><i class="fa fa-search"></i> View
                            Shipments</a></li>
                    </ul>
                </li>


                {% if user.is_officeUser or user.is_storeUser %}
                    <li class="treeview">
                        <a href="#">
                            <i class="fas fa-university"></i>
                            <span>Office</span>
                            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{% url 'mainSection:costfactor' %}"><i class="fas fa-hand-holding-usd"></i>
                                Shipment Cost Factor</a></li>
                            <li><a href="{% url 'mainSection:reviewshipment' %}"><i class="fa fa-barcode"></i> Review
                                Shipment</a></li>
                            <li><a href="{% url 'mainSection:viewproduct' %}"><i class="fa fa-search"></i> View Item</a>
                            </li>

                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-cubes"></i>
                            <span>Stores</span>
                            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{% url 'mainSection:grnstore' %}"><i class="fas fa-sign-in-alt"></i> Confirm
                                Shipment</a></li>
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fas fa-cash-register"></i>
                            <span> Transactions</span>
                            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{% url 'mainSection:loadCustomer' %}"><i class="fas fa-user-friends"> </i>
                                 Create Customer</a></li>
                             <li><a href="{% url 'mainSection:costfactor' %}"><i class="fas fa-file-invoice-dollar"> </i>
                                 Create Invoice</a></li>
                        </ul>
                    </li>
                {% else %}
                    <!-- Disable Links for the buyers -->
                    <li class="treeview">
                        <a href="">
                            <i class="fas fa-university"></i>
                            <span>Office</span>
                            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a><i class="fas fa-hand-holding-usd"></i> Shipment Cost Factor</a></li>
                            <li><a><i class="fa fa-barcode"></i> Review Shipment</a></li>
                            <li><a><i class="fa fa-search"></i> View Item</a></li>

                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="">
                            <i class="fa fa-cubes"></i>
                            <span>Stores</span>
                            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a><i class="fa fa-check-square-o"></i> Confirm Shipment</a></li>
                        </ul>
                    </li>
                {% endif %}


            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
    <div class="content-wrapper">


        {% block content %}

        {% endblock content %}


    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <p style="text-align:center"><b>Version</b> 1.0.0 <br/> <strong>Copyright &copy; 2018. Srimal Samarasooriya.
                All
                rights reserved. <a href="https://adminlte.io"> Theme by adminlte</a>.</strong></p>

        </div>
    </footer>


    <!-- jQuery 3 -->
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static '/js/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <!-- Morris.js charts -->
    <script src="{% static '/js/raphael.min.js' %}"></script>
    <script src="{% static '/js/morris.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static '/js/jquery.sparkline.min.js' %}"></script>
    <!-- jvectormap -->
    <script src="{% static '/js/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script src="{% static '/js/jquery-jvectormap-world-mill-en.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static '/js/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static '/js/moment.min.js' %}"></script>
    <script src="{% static '/js/daterangepicker.js' %}"></script>
    <!-- datepicker -->
    <script src="{% static '/js/bootstrap-datepicker.min.js' %}"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{% static '/js/bootstrap3-wysihtml5.all.min.js' %}"></script>
    <!-- Slimscroll -->
    <script src="{% static '/js/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static '/js/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static '/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static '/js/dashboard.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static '/js/demo.js' %}"></script>

    <script>
        window.onload = function () {
            document.getElementById("loading").style.display = "none";
        }
    </script>
    {% block scripts %}

    {% endblock scripts %}


</body>

</html>