authSection/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authSection'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
]

mainSection/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'mainSection'

urlpatterns = [
    path('home/', views.home, name="home"),
    path('createshipment/', views.createshipment, name="createshipment"),
    path('home/createshipment/saveshipment/', views.saveshipment, name="saveshipment"),
    path('fillshipment/', views.fillshipment, name="fillshipment"),
    path('saveproduct/', views.saveproduct, name="saveproduct"),
    path('viewhipment/', views.viewshipment, name="viewshipment"),
    path('reviewshipment/', views.reviewShipment, name="reviewshipment"),
    path('costfactor/', views.generateCostFactor, name="costfactor"),
    path('deleteshipmentdetail/<int:pk>', views.deleteshipmentdetail, name="deleteshipmentdetail"),
    path('finalizeshipment/', views.finalizeshipment, name="finalizeshipment"),
    path('updateproduct/<int:pk>/', views.updateproduct, name="updateproduct"),
    path('applyCost/', views.applyCost, name="applyCost"),
    path('viewproduct/', views.viewproduct, name="viewproduct"),
    path('grn/', views.grnstore, name="grnstore"),
    path('grn/<int:pk>/', views.updateproductgrn, name="updateproductgrn"),
    path('closeshipment', views.closeshipment, name="closeshipment"),
    path('customers/', views.loadCustomer, name="loadCustomer"),
    path('savecustomers/', views.savecustomers, name="savecustomers"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shadesProductUploader/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('mainSection.urls')),
    path('admin/', admin.site.urls),
    path('',include('authSection.urls')),
    
] 

mainSection/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.db import transaction
from django.http import JsonResponse
from django.template.loader import render_to_string
from decimal import *
from django.utils import timezone
from .decorators import office_required
from .forms import CreateShipmentForm, CreateProductForm, CreateShipmentDetails, CreateCostFactorForm, sellingPriceForm, GRNForm, CustomerForm
from .models import Shipment, ProductTypes, ShipmentDetail, Country, Products, ProductSize, ProductColour, ProducBrands, Customer, CustomerType

# global variables
shipment_list = None
shipmentItem_list = None
shipmentTotal = None
shipmentTotalQty = None
selectedShipment = None


########

# global Methods
# This function will accept a shipmentID and return a shipmentItemList


def getShipmentItemsList(shipmentId):
    if shipmentId is None:
        shipmentItem_list = None
    else:
        shipmentItem_list = ShipmentDetail.objects.filter(
            shipment=shipmentId, archived='0').select_related('product').select_related(
            'product__types')
    return shipmentItem_list


@login_required
def home(request):
    order_count = Shipment.objects.filter(buyer=request.user).count()
    products_count = ShipmentDetail.objects.filter(shipment__buyer= request.user).count()
    order_list = ShipmentDetail.objects.filter(shipment__buyer= request.user)#.annotate(total= Sum(F('indPrice') * F('qty')))['total'] or 0
    total_value =0
    for orderitem in order_list:
        total_value += (orderitem.indPrice * orderitem.qty)
    # no_bills = ShipmentDetail.objects.values('billNumber').distinct().count()
    no_bills = ShipmentDetail.objects.filter(shipment__buyer= request.user).values('billNumber').distinct().count()
    return render(request, '../templates/mainSection/home.html', {'order_count': order_count, 'products_count': products_count, 'total_value': total_value, 'no_bills': no_bills})


# This method will handle the create shipment request
@login_required
def createshipment(request):
    if request.method == "GET":

        # clearing the session form the system. so the New id will be facilitated
        request.session['shipmentID'] = None
        request.session.modified = True
        shipmentPointList = Country.objects.all()

        # shipmentNumber is defined by 'SHN-000' + next Id in the shipment Table
        try:
            nextId = Shipment.objects.all().count()   # trying to retrive the next primaryKey
            nextId += 1
        except:
            nextId = 1   # if the next ID is null define the record as the first
        form = CreateShipmentForm(
            initial={'shipmentNumber': 'SHN-000' + str(nextId)})  # creating the form with the shipment ID
    return render(request, '../templates/mainSection/createshipment.html', {'form': form, 'user': request.user, 'shipmentPointList': shipmentPointList})


# This method will handle the Save shipment request
@login_required
def saveshipment(request):
    if request.method == 'POST':
        form = CreateShipmentForm(request.POST)
        if form.is_valid():
            objShipment = form.save(commit=False)
            objCountry = get_object_or_404(Country, pk=request.POST.get('shipmentPointDropDown'))

            objShipment.shippingPoint = objCountry
            objShipment.buyer = request.user
            objShipment.userCreated = request.user
            objShipment.save()
        else:
            messages.error(request, form.errors)
        return redirect('mainSection:fillshipment')


@login_required
def viewshipment(request):
    # Retrieving The shipments which are open to fill.
    if request.user.is_officeUser or request.user.is_storeUser:
        shipment_list = Shipment.objects.all()
    else:
        shipment_list = Shipment.objects.filter(buyer=request.user)

    shipmentItem_list = None

    if request.method == 'GET':
        return render(request, '../templates/mainSection/viewshipment.html', {'shipments': shipment_list})

    if request.method == 'POST':
        # if the request if for a shipment that is selected in the dropdown the the following code block will execute
        if request.POST['shipmentDropDown']:

            # getting the shipmentID
            shipmentID = request.POST.get('shipmentDropDown')
            selectedShipment = Shipment.objects.select_related('shippingPoint').\
                select_related('buyer').get(id=shipmentID)  # Saving the selected Shipment object to passback to the template

            # getting the shipment List
            shipmentItem_list = getShipmentItemsList(shipmentID)
            shipmentTotal = 0
            shipmentTotalQty = 0
            shippingWeight = 0
            for shipment in shipmentItem_list:
                shipmentTotal += shipment.totalAmount
                shipmentTotalQty += shipment.qty
                shippingWeight += shipment.weight * shipment.qty

            shippingWeightKG = shippingWeight/1000

        else:
            messages.error(request, "Something went wrong.")

        return render(request, '../templates/mainSection/viewshipment.html',
                      {'shipments': shipment_list, 'shipmentDetails': shipmentItem_list, 'shipmentTotal': shipmentTotal,
                       'shipmentTotalQty': shipmentTotalQty, 'selectedShipment': selectedShipment,'shippingWeightKG':shippingWeightKG})


@login_required
@office_required
def reviewShipment(request):
    shipmentTotal = 0
    shipmentTotalQty = 0
    selectedShipment = 0
    shippingWeight = 0
    shippingWeightKG = 0

    shipment_list = Shipment.objects.filter(isCostapplied='False', isFinalized='1', isCostbaseFinalized='1')

    if request.method == 'GET':
        # if the request if for a shipment that is selected in the dropdown the the following code block will execute
        if request.GET.get('shipmentDropDown'):
            # clearing the session form the system. so the New id will be facilitated
            request.session['shipmentID'] = None
            request.session.modified = True
            shipmentID = request.GET.get('shipmentDropDown')  # getting the shipmentID
            shipmentItem_list = getShipmentItemsList(shipmentID)  # getting the shipment List
            selectedShipment = get_object_or_404(Shipment,
                                                 pk=shipmentID)  # Saving the selected Shipment object to passback to the template
            request.session['shipmentID'] = selectedShipment.id  # stroing the shipment Id for the save operation

        # since the session.flush is voided due to the the authentication issue, ShipmentID is set to null in the
        # session variable therefor need to check for null.
        elif request.method == 'GET' and request is not None and 'shipmentID' in request.session and request.session[
            'shipmentID'] is not None:
            print('here')

            shipmentItem_list = getShipmentItemsList(request.session['shipmentID'])
            selectedShipment = Shipment.objects.get(
                id=request.session['shipmentID'])



        else:
            shipmentItem_list = None
            selectedShipment = None

        if(shipmentItem_list is not None):
         for shipment in shipmentItem_list:
            shipmentTotal += shipment.totalAmount
            shipmentTotalQty += shipment.qty
            shippingWeight += shipment.weight * shipment.qty

        shippingWeightKG = shippingWeight / 1000
        print(shipmentTotal)
        print(shipmentTotalQty)
        print(shippingWeight)

        return render(request, '../templates/mainSection/reviewshipment.html',
                      {'shipments': shipment_list, 'shipmentDetails': shipmentItem_list, 'shipmentTotal': shipmentTotal,
                       'shipmentTotalQty': shipmentTotalQty, 'selectedShipment': selectedShipment,
                       'shippingWeightKG': shippingWeightKG})

    if request.method == 'POST':
        # if the request if for a shipment that is selected in the dropdown the the following code block will execute
        if request.POST.get('shipmentDropDown'):
            # getting the shipmentID and store it in sthe seesion
            shipmentID = request.POST.get('shipmentDropDown')
            request.session['shipmentID'] = shipmentID
            # Saving the selected Shipment object to passback to the template
            selectedShipment = Shipment.objects.get(pk=shipmentID)
            shipmentItem_list = getShipmentItemsList(shipmentID)

            shipmentTotal = 0
            shipmentTotalQty = 0
            shippingWeight = 0

            for shipment in shipmentItem_list:
                shipmentTotal += shipment.totalAmount
                shipmentTotalQty += shipment.qty
                shippingWeight += shipment.weight * shipment.qty

            shippingWeightKG = shippingWeight / 1000

    elif request.method == 'POST' and request is not None and 'shipmentID' in request.session and request.session['shipmentID'] is not None:
        shipmentItem_list = getShipmentItemsList(request.session['shipmentID'])
        selectedShipment = Shipment.objects.get(id=request.session['shipmentID'])
    else:
        shipmentItem_list = None
        selectedShipment = None

    return render(request, '../templates/mainSection/reviewshipment.html',
                  {'shipments': shipment_list, 'shipmentDetails': shipmentItem_list, 'shipmentTotal': shipmentTotal,
                   'shipmentTotalQty': shipmentTotalQty, 'selectedShipment': selectedShipment ,'shippingWeightKG':shippingWeightKG})


# This method will handle the fillshipment request
@login_required
def fillshipment(request):
    productCode = request.user.productCode
    nextId =None

    # shipmentNumber is defined by 'NuyerCode-000' + next Id in the shipment Table
    try:

templates/mainSection/costfactor.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block content %}




    <section class="content">
        <!-- Main content -->

        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <h1 class="box-title">
                    <strong> Cost
                        Shipment </strong></h1> - Assign a cost base to a shipments -
                <div class="box-tools pull-right">
                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
             <div class="box-body">
                {% if messages %}
                    <div class="row">
                        <div style="margin-left:auto; margin-right:auto;">
                            {% for message in messages %}
                                <div {% if message.tags %}
                                    class="alert alert-{{ message.tags }} alert-dismissible"{% endif %}>
                                    <a href="" style="text-decoration:none" class="close" data-dismiss="alert"
                                       aria-label="close">&times;</a>

                                    <p>{{ message }}</p>
                                </div>
                                </div>
                            {% endfor %}

                    </div>
                {% endif %}

                <form id='frmSearchShipment' action="{% url 'mainSection:costfactor' %}" method="POST"
                     >
                    {% csrf_token %}
                    <div class="box box-solid box-primary">
                        <div class="box-header with-border">
                            <h1 class="box-title"> 1. Search for a shipment</h1>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                        class="fa fa-minus"></i>
                                </button>
                            </div>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="col-md-4 center">

                                <div class="im-centered row">
                                    <div class="col-md-8 mb-6">
                                        <select name="shipmentDropDown" id="shipmentDropDown"
                                                class="form-control"
                                                required>
                                            <option value="">-Shipment Number-</option>
                                            {% for shipment in shipments %}
                                                {% if shipment.isClosed %}
                                                {% endif %}
                                                <option value="{{ shipment.id }}">{{ shipment.shipmentNumber }}
                                                </option>
                                            {% endfor %}

                                        </select>
                                    </div>

                                    <div class="col-md-2 mb-4">
                                        <input id="btnLoad" class="btn btn-primary" style="font-size: 14px;"
                                               type="submit"
                                               name="shipmentid" value="Search"/>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </form>
                <form id='frmCreateCost' action="{% url 'mainSection:costfactor' %}" method="POST"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="box box-solid box-primary">
                        <div class="box-header with-border">
                            <h1 class="box-title">2. Review the shipment</h1>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                        class="fa fa-minus"></i>
                                </button>
                            </div>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="row" style="margin-left:auto; margin-right:auto; margin-top: 2em">
                                <div class="col-md-3 mb-4">
                                    <strong> Shipment No - </strong>
                                    <p class="text-danger"><strong> {{ selectedShipment.shipmentNumber }} </strong>
                                    </p>
                                </div>

                                <div class="col-md-3 mb-4">
                                    <strong> Shipment Date -</strong>
                                    <p class="text-danger"><strong>  {{ selectedShipment.shipmentDate }} </strong>
                                    </p>
                                </div>


                                <div class="col-md-3 mb-4">
                                    <strong> Shipment Total -</strong>
                                    <p class="text-danger"><strong> {{ shipmentTotal|intcomma }}</strong></p>

                                </div>
                                <div class="col-md-3 mb-4">
                                    <strong> Shipment Qty - </strong>
                                    <p class="text-danger"><strong> {{ shipmentTotalQty|intcomma }} </strong></p>
                                </div>

                                <div class="col-md-3 mb-4">
                                    <strong> Shipping From - </strong>
                                    <p class="text-danger"><strong>  {{ selectedShipment.shippingPoint }}</strong>
                                    </p>
                                </div>

                                <div class="col-md-3 mb-4">
                                    <strong> Buyer - </strong>
                                    <p class="text-danger">
                                        <strong>  {{ selectedShipment.buyer.first_name }} {{ selectedShipment.buyer.last_name }} </strong>
                                    </p>
                                </div>

                                <div class="col-md-3 mb-4">
                                    <strong> Shipment Weight (Tot.) - </strong>
                                    <p class="text-danger"><strong>  {{ shippingWeightKG }} Kgs </strong></p>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <div class="box box-solid box-primary">
                        <div class="box-header with-border">
                            <h1 class="box-title">3. Assign the cost base</h1>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                        class="fa fa-minus"></i>
                                </button>
                            </div>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="row" style="margin-left:auto; margin-right:auto; margin-top: 2em">
                                <div class="col-md-2 mb-4">
                                    <strong> Cost Base - </strong>
                                    <p class="text-danger"><strong> {{ form.costBase }}</strong>
                                    </p>
                                </div>

                                <div class="col-md-4 mb-4">
                                    <strong> Cost File - </strong>
                                    <p class="text-danger"><strong> {{ form.costFile }}</strong>
                                    </p>
                                </div>
                                <div class="col-md-4 mb-4">
                                    <strong> Note - </strong>
                                    <p class="text-danger"> <strong> Please make sure that cost file is named as  {{ selectedShipment.shipmentNumber }}.xls </strong>
                                    </p>
                                </div>

                            </div>
                            <div class="row">
                                <div style="margin-left:auto; margin-right:20px;">
                                    <button id="btnFinalize" class="btn btn-danger" type="submit" name="shipmentid"
                                            data-toggle="modal"
                                            data-target="#confirmModal">Update Shipment
                                    </button>
                                </div>
                            </div>
                        </div>

                        <!-- /.box-body -->
                    </div>
                </form>
                <!-- /.box-body -->
                <!-- end of the Grid section -->
            </div><!-- /.box-body -->
            <div class="box-footer">

            </div><!-- box-footer -->

        </div>



    </section>
    <!-- /.content -->

{% endblock content %}


{% block scripts %}
    <script src="{% static '/js/select2.full.min.js' %}"></script>
    <script src="{% static '/js/jquery.dataTables.min.js' %}"></script>

    <script>

        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()
            //Date picker - Two lines is to set the default date.
            $("#datepicker").datepicker("setDate", new Date());
            $('#datepicker').datepicker({autoclose: true,});

        })
    </script>

    <script>
        $('#frmCreateCost').submit(function () {
            document.getElementById("loading").style.display = "visible";
        });
    </script>
{% endblock scripts %}

templates/mainSection/createshipment.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Create
        <small>Shipment</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Shipment</a></li>
        <li class="active">Create Shipment</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="box box-default">
        <div class="container">
            <form id='frmCreateShipment' action="{% url 'mainSection:saveshipment' %}" method="POST">
                {% csrf_token %}

                <h4 style="text-align: center; margin-top: 2em">Shipment Details</h4>

                <div class="box-body">
                    <h6 style="text-align: center; font-weight: bold;">Shipment
                        No: </h6>
                    <div class="im-centered row">
                        <label id="shipmentNumber" style="margin-right: auto; margin-left: auto;">{{form.shipmentNumber}}
                        </label>
                    </div>
                <h6 style="text-align: center; font-weight: bold;">Shipment
                        point: </h6>
                    <div class="im-centered row">
                            <div class="col-md-3 mb-4" style="margin-right: auto; margin-left: auto;">
                                <select name="shipmentPointDropDown" id="shipmentPointDropDown" class="form-control"
                                        required>
                                    <option value="">-Select Shipment Point-</option>
                                    {% for shipmentPoint in shipmentPointList %}
                                        <option value="{{ shipmentPoint.id }}">{{ shipmentPoint.shippingPoint }}
                                        </option>
                                    {% endfor %}

                                </select>

                            </div>
                        </div>
                    <h6 style="text-align: center; font-weight: bold;">Shipment Date:</h6>
                    <div class="im-centered row">
                        {{form.shipmentDate}}
                    </div>
                    <div class="d-flex flex-row justify-content-center align-items-center">
                        <button id="btnCreateShipment" type="submit" class="btn btn-danger"> Create Shipment</button>
                    </div>
                </div>

            </form>
            {% if messages %}
            <div class="row">
                <div class="d-flex flex-row justify-content-center align-items-center">
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        <p>{{ message }}</p>
                    </div>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {% endfor %}
                </div>

            </div>
            {% endif %}
        </div>
    </div>

</section>
<!-- /.content -->

{% endblock content %}


{% block scripts %}
<script src="{% static '/js/select2.full.min.js' %}"></script>
<script src="{% static '/js/jquery.dataTables.min.js' %}"></script>

<script>

    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()
        //Date picker - Two lines is to set the default date.
        $("#datepicker").datepicker("setDate", new Date());
        $('#datepicker').datepicker({ autoclose: true, });
       
    })
</script>


<script>
    $("frmCreateShipment").submit(function (e) {
    $("#fillShipmentLink").removeClass('btn btn-primary disabled');
    });
</script>
{% endblock scripts %}

templates/mainSection/home.html
{% extends 'base.html' %}
{% load humanize %}



{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Welcome
            <bold>{{ user.username|title }},</bold>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
         <!-- Info boxes -->
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fas fa-box-open"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Total shipments</span>
              <span class="info-box-number">{{ order_count }}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fas fa-tshirt"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Total Products</span>
              <span class="info-box-number">{{ products_count }}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->

        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>

        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fas fa-file-invoice-dollar"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Total shipment Value</span>
              <span class="info-box-number">{{ total_value |intcomma }}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fas fa-file-invoice"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Number of bills</span>
              <span class="info-box-number">{{ no_bills }}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
        <!-- /.row -->

    </section>
    <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}

templates/mainSection/invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>